services:
  corems_dev:
    container_name: corems_dev
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev
    init: true
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      COREMS_DATABASE_URL: "postgresql+psycopg2://coremsappuser:coremsapppnnl@molformdb:5432/coremsapp"
    depends_on:
      molformdb:
        condition: service_healthy
    networks:
      - corems-network

networks:
  corems-network:
    external: true